### ISSUE TITLE
Improvements tracker

### ISSUE THREAD

**Issue by axelmoreen** [axelmoreen/AnkiBuddy#3]
Putting miscellaneous ideas for improvements here.

Small features:
- [ ] Field Name in the Write Answer options (currently Enabled all the time)
- [ ] "I was right" answer button when there is a wrong answer.
- [ ] Keyboard shortcuts for matching and multiple-choice
- [ ] Be able to change sound volume?

Not so small:
- [ ] Subsets rework. Be able to use subsets as "Filters" so you could use multiple at a time. Also allow the user to create their own subsets, with cards they choose. Also create a subset that is based on the same field values, like Part of Speech.
- [ ] Presets for the Questions Wizard
- [ ] Testing mode, where you have to answer several questions and then you only see the results afterwards.
- [ ] Dynamically load the question widgets, add them to the options menu, etc. Do not make assumptions about what kinds of questions widgets are present, this would make it simpler to add more widgets in the future or allow you to create question widgets from another add-on.
- [ ] Move everything to web views, away from the QT layouts. At the very least, the question widgets / practice mode. This change would allow the buttons to support furigana, would make appearances more consistent between the question labels and the rest of the UI, and allow for better and more effortless layouts. It would be more consistent with the design of Anki as well.
- [ ] Maybe a cloze mode system can be devised. Currently it is possible to do cloze if the card has a cloze field, but this doesn't always work as intended. For example, in the Core2k set, the verbs that are in cloze sentences do not have an answer field with just a conjugated verb, though it is conjugated in the sentence with the answer.
